// Generated by swagger/tools/gen-stub --doc openapi.json --src ./api/oapigen --dst ./api
package api

// ApiController :
type ApiController struct {
	*EmojiController
}

// NewApiController :
func NewApiController() *ApiController {
	return &ApiController{
		EmojiController: NewEmojiController(),
	}
}
